# Generated by Django 5.2.7 on 2025-10-15 13:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project', max_length=255, verbose_name='project name')),
                ('key', models.CharField(help_text='Short project identifier (e.g., PRJ-001)', max_length=10, unique=True, verbose_name='project key')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project', null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', help_text='Current status of the project', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the project', max_length=10, verbose_name='priority')),
                ('start_date', models.DateField(blank=True, help_text='Planned start date of the project', null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='Planned end date of the project', null=True, verbose_name='end date')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget allocated for the project', max_digits=15, null=True, verbose_name='budget')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Project completion percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progress')),
                ('is_template', models.BooleanField(default=False, help_text='Whether this project is a template for new projects', verbose_name='is template')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this project is visible to all users', verbose_name='is public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the project was marked as completed', null=True, verbose_name='completed at')),
                ('created_by', models.ForeignKey(help_text='User who created the project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department responsible for the project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='myapp.department')),
                ('owner', models.ForeignKey(help_text='User who owns the project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-created_at'],
                'permissions': [('view_all_projects', 'Can view all projects'), ('export_project', 'Can export project data'), ('manage_project_members', 'Can add/remove project members')],
            },
        ),
    ]
