# Generated by Django 5.2.7 on 2025-10-16 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_projectmember_project_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title of the task', max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task', null=True, verbose_name='description')),
                ('due_date', models.DateTimeField(blank=True, help_text='When this task is due', null=True, verbose_name='due date')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the task', max_length=10, verbose_name='priority')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', help_text='Current status of the task', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='User assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='myapp.project')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Attached file', upload_to='task_attachments/%Y/%m/%d/', verbose_name='file')),
                ('file_name', models.CharField(help_text='Original name of the uploaded file', max_length=255, verbose_name='file name')),
                ('file_size', models.PositiveIntegerField(help_text='Size of the file in bytes', verbose_name='file size')),
                ('content_type', models.CharField(help_text='MIME type of the file', max_length=100, verbose_name='content type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='The task this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='myapp.task')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task attachment',
                'verbose_name_plural': 'task attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='myapp_task_project_7cff40_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='myapp_task_assigne_dc4653_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='myapp_task_due_dat_68da50_idx'),
        ),
    ]
