# Generated by Django 5.2.7 on 2025-10-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_options_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_lead', models.BooleanField(default=False, help_text='Whether this assignee is the lead for the task')),
            ],
            options={
                'verbose_name': 'task assignment',
                'verbose_name_plural': 'task assignments',
            },
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='myapp_task_assigne_dc4653_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assignee',
            field=models.ForeignKey(help_text='User assigned to the task', on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(help_text='The task being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='myapp.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(help_text='Users assigned to this task', related_name='assigned_tasks', through='myapp.TaskAssignment', through_fields=('task', 'assignee'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'assignee')},
        ),
    ]
